// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Predict.proto

#include "Predict.pb.h"
#include "Predict.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace pytorchserving {

static const char* Predictor_method_names[] = {
  "/pytorchserving.Predictor/Predict",
};

std::unique_ptr< Predictor::Stub> Predictor::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Predictor::Stub> stub(new Predictor::Stub(channel));
  return stub;
}

Predictor::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Predict_(Predictor_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Predictor::Stub::Predict(::grpc::ClientContext* context, const ::pytorchserving::PredictRequest& request, ::pytorchserving::PredictResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Predict_, context, request, response);
}

void Predictor::Stub::experimental_async::Predict(::grpc::ClientContext* context, const ::pytorchserving::PredictRequest* request, ::pytorchserving::PredictResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, std::move(f));
}

void Predictor::Stub::experimental_async::Predict(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::pytorchserving::PredictResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::pytorchserving::PredictResponse>* Predictor::Stub::AsyncPredictRaw(::grpc::ClientContext* context, const ::pytorchserving::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::pytorchserving::PredictResponse>::Create(channel_.get(), cq, rpcmethod_Predict_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::pytorchserving::PredictResponse>* Predictor::Stub::PrepareAsyncPredictRaw(::grpc::ClientContext* context, const ::pytorchserving::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::pytorchserving::PredictResponse>::Create(channel_.get(), cq, rpcmethod_Predict_, context, request, false);
}

Predictor::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Predictor_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Predictor::Service, ::pytorchserving::PredictRequest, ::pytorchserving::PredictResponse>(
          std::mem_fn(&Predictor::Service::Predict), this)));
}

Predictor::Service::~Service() {
}

::grpc::Status Predictor::Service::Predict(::grpc::ServerContext* context, const ::pytorchserving::PredictRequest* request, ::pytorchserving::PredictResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace pytorchserving

